### ISSUE TITLE
Daily/Weekly/Monthly Reminders

### ISSUE THREAD

**Issue by Davouro** [floriankorstanje/ByeBot#3]
You could do your reminder, whatever it is but if you add [Daily/Weekly/Monthly] at the end they will notify you according to that:

Format:
$remindme [add] [time/date] [reminder] [interval]

Examples:
Regular reminder (not daily weekly monthly)
$remindme add 20/3/21 date "Test"

Monthly Reminder
$remindme add 20/3/21 date "Test" monthly
//Will remind user on the 20th of every month

Daily Reminder
$remindme add 5 hours "Test" daily 
//Will remind user at whatever time is in 5 hours every day

**Comment by floriankorstanje** [comment]
Can't add this because of the way I made the reminders, in short: you add reminder, it calculates time at which it finishes, adds that to a file, bot checks every 5 seconds if any reminders have expired. If I wanted to add this I'd have to add a lot of reminder entries to the file each `interval` apart. This would take up a lot of the files, and if you wanted to stop it you'd have to remove all the entries manually
